# Generated by Django 3.2.2 on 2021-05-09 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', null=True, upload_to='store_image/')),
                ('favorite', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.datetime(2021, 5, 9, 6, 11, 54, 253223, tzinfo=utc))),
            ],
        ),
    ]
