# Generated by Django 3.2.2 on 2021-05-09 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 6, 15, 36, 93121, tzinfo=utc)),
        ),
    ]
