# Generated by Django 3.2.2 on 2021-05-09 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0002_alter_book_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 6, 38, 23, 97318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./tp_book/store_image/'),
        ),
    ]
